apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: sim-cluster-{{.Iteration}}
  namespace: {{.Namespace}}
  annotations:
    cluster.x-k8s.io/paused: "true"
    simulation: "true"
    created-by: "kube-burner"
  labels:
    simulation: "true"
    iteration: "{{.Iteration}}"
    batch: "scale-test"
spec:
  paused: true
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local

